# Generated by Django 4.0.4 on 2022-05-03 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Body', models.CharField(max_length=10000)),
                ('Published', models.BooleanField()),
                ('Archived', models.BooleanField()),
                ('Created', models.DateTimeField()),
                ('Updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Author', models.CharField(max_length=200)),
                ('Body', models.CharField(max_length=1000)),
                ('Created', models.DateTimeField()),
                ('Updated', models.DateTimeField()),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.blogpost')),
            ],
        ),
    ]
