# Generated by Django 4.0.4 on 2022-05-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Updated',
            field=models.DateTimeField(null=True),
        ),
    ]
