# Generated by Django 4.0.4 on 2022-05-04 18:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blogpost_created_alter_blogpost_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Body',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='Created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 4, 14, 58, 55, 217430)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=50)),
                ('BlogPostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.blogpost')),
            ],
        ),
    ]
